DATE_COLUMN_NAME  = "<DATE>"
TIME_COLUMN_NAME  = "<TIME>"
PRICE_COLUMN_NAME = "<CLOSE>"

USEFUL_COLUMNS_NAMES   = [DATE_COLUMN_NAME,TIME_COLUMN_NAME,PRICE_COLUMN_NAME]
LISTED_COMPANIES_NAMES = ['BBAS3','BBDC4','ITUB4','PETR4','VALE3']

PRE_START_DATE = (2019, 4,10)
START_DATE     = (2019, 5, 6)
END_DATE       = (2019, 11,21)
START_MONEY    = 1e5
RESULTS_FILE   = 'data_equity_file.csv'



