DATE_COLUMN_NAME  = "<DATE>"
TIME_COLUMN_NAME  = "<TIME>"
PRICE_COLUMN_NAME = "<CLOSE>"

USEFUL_COLUMNS_NAMES   = [DATE_COLUMN_NAME,TIME_COLUMN_NAME,PRICE_COLUMN_NAME]
LISTED_COMPANIES_NAMES = ['BBAS3','BBDC4','ITUB4','PETR4','VALE3']

